version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./instagram_clone.db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8001
    command: npm start
